### ISSUE TITLE
question: what do you do when you have non-inline html & scss?

### ISSUE THREAD

**Issue by dalu** [urish/angular-static-site#1]
```ts
import {Component} from '@angular/core';

@Component({
    selector:'app-root',
    templateUrl:'./app.component.html',
    styleUrls:['./app.component.scss']
})
export class AppComponent {
}
```

when doing ts-node build.ts
I'm getting
```
$ ts-node build.ts

/home/darko/WebstormProjects/static-angular/node_modules/packages/platform-browser-dynamic/esm5/src/compiler_factory.js:34
    function CompilerImpl(injector, _metadataResolver, templateParser, styleCompiler, viewCompiler, ngModuleCompiler, summaryResolver, compileReflector, compilerConfig, console) {
             ^
Error: No ResourceLoader implementation has been provided. Can't read the url "app.component.html"
    at Object.get (/home/darko/WebstormProjects/static-angular/node_modules/packages/platform-browser-dynamic/esm5/src/compiler_factory.js:34:14)
    at DirectiveNormalizer._fetch (/home/darko/WebstormProjects/static-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:3186:43)
    at DirectiveNormalizer._preParseTemplate (/home/darko/WebstormProjects/static-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:3241:29)
    at DirectiveNormalizer.normalizeTemplate (/home/darko/WebstormProjects/static-angular/node_modules/@angular/compiler/bundles/compiler.umd.js:3221:36)
    at CompileMetadataResolver.loadDirectiveMetadata (/home/darko/WebstormProjects/static-angular/node_modules/packages/compiler/esm5/src/metadata_resolver.js:363:44)
    at /home/darko/WebstormProjects/static-angular/node_modules/packages/compiler/esm5/src/jit/compiler.js:241:66
    at Array.forEach (<anonymous>)
    at /home/darko/WebstormProjects/static-angular/node_modules/packages/compiler/esm5/src/jit/compiler.js:240:16
    at Array.forEach (<anonymous>)
    at JitCompiler._loadModules (/home/darko/WebstormProjects/static-angular/node_modules/packages/compiler/esm5/src/jit/compiler.js:237:30)
```

**Comment by dalu** [comment]
Hi Uri,
for now I decided to go old-fashioned way of true SSR, aka AngularJS embedded into server rendered html.

But I have not given up on this yet and will continue on this soonTM.
I will post here if I find out anything new. I could imagine that routing will be another problem, if you have more than just an index page (or view).

For fusebox this can be solved with ng-fused (they rewrite the uris to be wrapped in a `require()` statement).

Thanks for now, I'll be back
- Darko

**Comment by urish** [comment]
Awesome, good luck with your project! 

Let me know if there is anything I can help with :-)
